<footer>
    <div class="newsletter"><a href="#">grab our newsletter</a></div>
    <div class="bottom-footer">
        <div class="footer-logo"><a href="#"><img src="images/footer-logo.png" alt=""></a></div>
        <ul class="footer-nav nav">
            <li><a href="#" class="active"><span>BEDROOM</span></a></li>
            <li><a href="#"><span>LIVING ROOM</span></a></li>
            <li><a href="#"><span>OFFICE</span></a></li>
            <li><a href="#"><span>Kitchen</span></a></li>
            <li><a href="#"><span>Bathroom</span></a></li>
        </ul>

        <ul class="footer-social-icon">
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
        </ul>
        <span class="clear"></span>
    </div>
</footer>