<header class="animated" data-animation="fadeInDown" data-animation-delay="100">
    <div class="logo pull-left"><a href="#"><img src="images/logo.png" alt=""></a></div>
    <div class="main-menu pull-right">
        <div class="nav-wrap pull-left">
            <a href="#" class="menu-btn" onclick="slideToggle()"><span></span><span></span></a>
            <ul class="nav">
                <li><a href="#" class="active"><span>bedroom</span></a></li>
                <li><a href="#"><span>living room</span></a></li>
                <li><a href="#"><span>office</span></a></li>
                <li><a href="#"><span>Kitchen</span></a></li>
                <li><a href="#"><span>Bathroom</span></a></li>
            </ul>
        </div>
        <ul class="header-icons pull-left">
            <li><a href=""><img src="images/icons/search.png" alt=""></a></li>
            <li><a href=""><img src="images/icons/heart.png" alt=""></a></li>
            <li><a href="" class="cart"><img src="images/icons/cart.png" alt=""><span class="no-of-items">2</span></a></li>
        </ul>
    </div>
    <span class="clear"></span>
</header>